### ISSUE TITLE
Unable to run the test scrip

### ISSUE THREAD

**Issue by dstollie** [daanpeer/bunq.js#1]
Im currently trying your package with the script you wrote in the example folder. Instead of adding this dependency to my code base I added it trough npm.  This is how my require currently looks like:

```javascript
// index.js
const Bunq = require('bunq.js')
const ursa = require('ursa')
const config = require('./config.js')
```

```json
// package.json
{
  "name": "bunq-js-example",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "ursa": "^0.9.4",
    "bunq.js": "^0.0.2"
  },
  "scripts": {
    "start": "node index.js",
    "lint": "yarn standard"
  },
  "devDependencies": {
    "jest": "^19.0.2",
    "standard": "^10.0.1"
  }
}

```

But for unfortunately im getting the following error when running the script

``` 
$ node index.js 
module.js:472
    throw err;
    ^

Error: Cannot find module 'bunq'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/dennisstolmeijer/Code/offline/bunq-js-example/index.js:1:76)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
error Command failed with exit code 1.
```

Also when I go to the bunq.js folder in the node_modules folder I see you make use of the import/export features from es6. As far as I know, node currently does not support import/export. This might also be a problem :).

Tell me how to fix this plox

**Comment by daanpeer** [comment]
@dstollie This should be resolved now ;)
